### ISSUE TITLE
Vulnerability in jsonwebtoken

### ISSUE THREAD

**Issue by Araxeus** [PlasmoHQ/mozilla-addons-api#59]
https://github.com/PlasmoHQ/mozilla-addons-api/blob/ea32dfa519e75f7215c30685eaa723eac4940fb2/package.json#L39

* https://security.snyk.io/package/npm/jsonwebtoken/8.5.1

* https://github.com/auth0/node-jsonwebtoken/blob/master/CHANGELOG.md#900---2022-12-21
  (don't forget to check out the migration guide)

![image](https://user-images.githubusercontent.com/78568641/212546336-dba1e5e4-6176-4a5d-9269-861313e60ffd.png)

to be fair, I think the usage here is fine and won't be affected, but I'll leave it for someone more experienced in cryptography
https://github.com/PlasmoHQ/mozilla-addons-api/blob/ea32dfa519e75f7215c30685eaa723eac4940fb2/src/index.ts#L152-L156

**Comment by louisgv** [comment]
closed in https://github.com/PlasmoHQ/bpp/releases/tag/v3.2.0
